image: openjdk:11
stages:
  - test

variables:
  PROJECT_NAME: algorithmia-java
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  RUNNING_ON_BUILD_SERVER: "true"

test:unit-code-coverage:
  stage: test
  image: algorithmiahq/sbt-builder:11.0.6_1.3.8_2.13.1
  script:
  - sbt compile
  - sbt test
